### ISSUE TITLE
Error .miz

### ISSUE THREAD

**Issue by Heater711** [evogelsa/DCS-real-weather#4] opened 2021-11-15 09:12 UTC
WORLDGENERAL: loading mission from: "C:\Users\Administrator\Saved Games\caucaso\Slmod\Missions\Caucaso_1.2_SOP_real_weather.miz"
2021-11-15 09:05:38.964 INFO    APP: use_xRay: yes
2021-11-15 09:05:38.964 INFO    APP: netfm_enable_coeff_switching: yes
2021-11-15 09:05:39.013 ERROR   Dispatcher: Mission Load Error: Cannot mission: luaL_loadbuffer() returned [string "mission"]:84014: '}' expected (to close '{' at line 2) near '<eof>'

**Comment by evogelsa** [comment] 2021-11-15 13:55
I think this is a duplicate of #2. Try adding a cloud preset to the mission you're updating. Feel free to reopen if this is not the case.

**Closed by evogelsa** 2021-11-15 13:55 UTC
